name: Move new issues into Triage

on:
  issues:
    types:
      - opened

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: ActionsProject
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
